"use client";
import React from "react";
import { ResourceCardFortAwesome } from "@/components";
import {
  faStarOfLife,
  faBriefcaseMedical,
  faFaceSmile,
  faHeart,
  faHeadSideMask,
  faUtensils,
  faHandsBubbles,
  faBowlFood,
  faPersonWalking,
  faDumbbell,
  faEarthAmericas,
  faKiwiBird,
  faDove,
  faHorseHead,
  faPuzzlePiece,
  faChildDress,
  faChild,
  faChalkboardUser,
  faShieldCat,
  faCow,
  faChildReaching,
  faStore,
  faMasksTheater,
  faSchool,
  faBuildingColumns,
  faPaintbrush,
  faDroplet,
  faPalette,
  faMusic,
  faIcons,
  faGuitar,
  faDemocrat,
  faNewspaper,
  faLaptopFile,
  faGlobe,
  faComputer,
  faMicrophone,
  faPenToSquare,
  faPen,
  faBookOpenReader,
  faFileVideo,
  faVideo,
  faLinesLeaning,
  faBookOpen,
  faBookAtlas,
  faAppleWhole,
  faAtom,
  faMicroscope,
  faBook,
  faBookBible,
  faBookTanakh,
  faBookJournalWhills,
  faHandsHoldingChild,
  faRecycle,
  faCat,
  faOtter,
  faHippo,
  faHorse,
  faLeaf,
  faMountainCity,
  faMountainSun,
  faPlantWilt,
  faTree,
} from "@fortawesome/free-solid-svg-icons";
import { faWindowRestore } from "@fortawesome/free-regular-svg-icons";

const data = [
  {
    title: "Language & Communication",
    resources: [
      {
        id: 3763,
        name: "Tips to Improve Public Speaking Skills in Children",
        url: "https://tist.school/blog/tips-improve-public-speaking-skills-children",
        color: "#007bff",
        icon: faMicrophone,
      },
      {
        id: 3759,
        name: "Public Speaking Topics and Ideas for Students",
        url: "https://globalindianschool.org/my/blog-details/list-of-public-speaking-topics-and-ideas-for-students/",
        color: "#dc3545",
        icon: faMicrophone,
      },
      {
        id: 3753,
        name: "Public Speaking for Kids: 30 Topic Ideas for 30 Days",
        url: "https://speechblubs.com/blog/public-speaking-for-kids/",
        color: "#28a745",
        icon: faMicrophone,
      },
      {
        id: 3749,
        name: "Super Simple Rhymes",
        url: "https://supersimple.com/super-simple-songs/",
        color: "#ffc107",
        icon: faChildReaching,
      },
      {
        id: 3742,
        name: "Famous Rhyming Poems",
        url: "https://www.momjunction.com/articles/rhyming-poems-for-kids_001049871/",
        color: "#fd7e14",
        icon: faChildReaching,
      },
      {
        id: 3740,
        name: "Short Poems For Kids",
        url: "https://www.planetspark.in/blogs/english-poems-for-kids",
        color: "#6f42c1",
        icon: faChildReaching,
      },
      {
        id: 3727,
        name: "25 Creative Writing Prompts for Kids",
        url: "https://www.nightzookeeper.com/blog/articles/25-creative-writing-prompts-for-kids-to-get-imaginations-flowing",
        color: "#17a2b8",
        icon: faPenToSquare,
      },
      {
        id: 3713,
        name: "52 Creative Drawing Prompts for Kids",
        url: "https://www.funsensoryplay.com/52-creative-drawing-prompts-for-kids/?srsltid=AfmBOooocVSNFRuDQwpyPhxjzEXT5ik8qIeJa3T0Gp37pCXmnrFaYLo5",
        color: "#e83e8c",
        icon: faPen,
      },
      {
        id: 3712,
        name: "Creative Writing & Drawing",
        url: "https://www.edutopia.org/blog/thoughtful-creative-writing-through-art-denise-cassano",
        color: "#343a40",
        icon: faPen,
      },
      {
        id: 3703,
        name: "Reading Aloud & Storytelling",
        url: "https://www.tulikabooks.com/early-readers/read-aloud-stories-english.html",
        color: "#20c997",
        icon: faBookOpenReader,
      },
      {
        id: 3702,
        name: "Reading Aloud & Storytelling",
        url: "https://www.twinkl.co.in/blog/fourteen-fabulous-stories-read-aloud",
        color: "#007bff",
        icon: faBookOpenReader,
      },
      {
        id: 3699,
        name: "Reading Aloud & Storytelling",
        url: "https://www.readingrockets.org/topics/reading-aloud",
        color: "#dc3545",
        icon: faBookOpenReader,
      },
    ],
  },
  {
    title: "Fun & Edutainment",
    resources: [
      {
        id: 3766,
        name: "Virtual Travel for Kids",
        url: "https://thehaphazardtraveler.com/virtual-travel-for-kids-field-trips-museums-zoos/",
        color: "#007bff",
        icon: faEarthAmericas,
      },
      {
        id: 3764,
        name: "Virtual Field Trips to the Zoo",
        url: "https://www.kaixr.com/post/virtual-field-trips-zoo",
        color: "#dc3545",
        icon: faKiwiBird,
      },
      {
        id: 3762,
        name: "Children’s Museums, Aquariums, and Zoos to Virtually Explore",
        url: "https://coast2coastwithkids.com/10-childrens-museums-aquariums-and-zoos-to-virtually-explore/",
        color: "#28a745",
        icon: faDove,
      },
      {
        id: 3761,
        name: "Virtual Zoo & Museum Tours",
        url: "https://louisvilleeast.macaronikid.com/articles/5e750eb26c3c622e02538c7c/free-virtual-tours-animal-cams-and-virtual-field-trips",
        color: "#ffc107",
        icon: faHorseHead,
      },
      {
        id: 3760,
        name: "Puzzle Games",
        url: "https://www.digipuzzle.net/education/winter/index.htm#google_vignette",
        color: "#fd7e14",
        icon: faPuzzlePiece,
      },
      {
        id: 3756,
        name: "Riddles for Kids",
        url: "https://whosmarted.com/riddles-for-kids/",
        color: "#6f42c1",
        icon: faChildDress,
      },
      {
        id: 3755,
        name: "Fun and Challenging Riddles for Kids",
        url: "https://www.pocoyo.com/play/riddles",
        color: "#17a2b8",
        icon: faChild,
      },
      {
        id: 3754,
        name: "Fun What Am I Riddles for Kids",
        url: "https://www.splashlearn.com/blog/what-am-i-riddles-for-kids-with-answers/",
        color: "#e83e8c",
        icon: faChalkboardUser,
      },
      {
        id: 3752,
        name: "Puzzle Games & Riddles",
        url: "https://www.prodigygame.com/main-en/blog/riddles-for-kids/",
        color: "#343a40",
        icon: faPuzzlePiece,
      },
      {
        id: 3751,
        name: "Best Educational Cartoons That Make Learning Fun for Kids",
        url: "https://www.anideos.com/best-educational-cartoons",
        color: "#20c997",
        icon: faShieldCat,
      },
      {
        id: 3750,
        name: "Educational Cartoons & Animated Shows",
        url: "https://www.splashlearn.com/blog/best-educational-cartoons-for-kids/",
        color: "#007bff",
        icon: faCow,
      },
      {
        id: 3747,
        name: "Digital Storytelling Tools for Students",
        url: "https://khiredkids.com/digital-storytelling-tools-for-students/",
        color: "#dc3545",
        icon: faChildReaching,
      },
      {
        id: 3746,
        name: "Best Digital Storytelling Sites and Apps",
        url: "https://www.teachthought.com/technology/digital-storytelling-apps-and-websites/",
        color: "#28a745",
        icon: faWindowRestore,
      },
      {
        id: 3743,
        name: "Interactive Storytelling Apps",
        url: "https://www.commonsensemedia.org/lists/storytelling-apps",
        color: "#ffc107",
        icon: faStore,
      },
    ],
  },
  {
    title: "Digital Literacy & Tech Skills",
    resources: [
      {
        id: 3686,
        name: "Safe Online Behavior & Digital Etiquette",
        url: "https://www.kaspersky.com/resource-center/preemptive-safety/what-is-netiquette",
        color: "#007bff",
        icon: faBuildingColumns,
      },
      {
        id: 3685,
        name: "Safe Online Behavior & Digital Etiquette",
        url: "https://www.talktoangel.com/blog/digital-etiquette#:~:text=Protect%20others'%20privacy%20and%20security.&text=Avoid%20sharing%20sensitive%20or%20confidential,protect%20your%20own%20digital%20identity.",
        color: "#dc3545",
        icon: faLaptopFile,
      },
      // {
      //   id: 3683,
      //   name: "Basic Coding (Block-based, Scratch)",
      //   url: "https://tinker.ly/scratch-programming-what-are-code-blocks/",
      //   color: "#28a745",
      //   icon: faSchool,
      // },
      {
        id: 3682,
        name: "Basic Coding (Block-based, Scratch)",
        url: "https://www.geeksforgeeks.org/basics-of-scratch-programming/",
        color: "#ffc107",
        icon: faSchool,
      },
      {
        id: 3680,
        name: "Basic Coding (Block-based, Scratch)",
        url: "https://subjectguides.york.ac.uk/coding/scratch#:~:text=Scratch%20is%20a%20block%20based,or%20a%20sound%20to%20play.",
        color: "#fd7e14",
        icon: faBuildingColumns,
      },
      // {
      //   id: 3678,
      //   name: "Introduction to Computers & Internet Safety",
      //   url: "https://islingtonchildcare.proceduresonline.com/chapters/p_computer_safety.html",
      //   color: "#6f42c1",
      //   icon: faGlobe,
      // },
      {
        id: 3677,
        name: "Introduction to Computers & Internet Safety",
        url: "https://www.vedantu.com/computer-science/introduction-to-computer",
        color: "#17a2b8",
        icon: faComputer,
      },
      // {
      //   id: 3676,
      //   name: "Introduction to Computers & Internet Safety",
      //   url: "https://peda.net/kenya/ass/subjects2/computer-studies/form-1/itc2",
      //   color: "#e83e8c",
      //   icon: faComputer,
      // },
      {
        id: 3672,
        name: "Introduction to Computers & Internet Safety",
        url: "https://edu.gcfglobal.org/en/internetsafety/introduction-to-internet-safety/1/",
        color: "#343a40",
        icon: faComputer,
      },
    ],
  },
  {
    title: "Creativity & Performing Arts",
    resources: [
      // {
      //   id: 3745,
      //   name: "Free, fun drama games",
      //   url: "https://www.britishcouncil.in/blog/free-fun-drama-games-help-your-child-learn-english",
      //   color: "#007bff",
      //   icon: faMasksTheater,
      // },
      {
        id: 3744,
        name: "Drama Activities",
        url: "https://www.playfulhomeducation.com/post/how-to-do-drama-activities-with-kids-at-home-indian-themes-and-story-ideas",
        color: "#dc3545",
        icon: faSchool,
      },
      {
        id: 3741,
        name: "Puppetry & Drama",
        url: "https://www.youtube.com/@SanMarcosPublicLibrary",
        color: "#28a745",
        icon: faBuildingColumns,
      },
      {
        id: 3738,
        name: "Coloring Games",
        url: "https://www.crazygames.com/t/coloring",
        color: "#ffc107",
        icon: faPaintbrush,
      },
      {
        id: 3736,
        name: "Online coloring pages for kids",
        url: "https://www.coloringpages-forkids.com/",
        color: "#fd7e14",
        icon: faDroplet,
      },
      {
        id: 3734,
        name: "Drawing & Coloring Activities",
        url: "https://www.roomrecess.com/pages/ColoringPagesForKids.html",
        color: "#6f42c1",
        icon: faPalette,
      },
      {
        id: 3730,
        name: "Dance for Kids India",
        url: "https://www.youtube.com/playlist?list=PLMAiskWkAi93cMONWWNcqKqcvk-e3JZdi",
        color: "#17a2b8",
        icon: faMusic,
      },
      {
        id: 3725,
        name: "Music & Dance for Kids",
        url: "https://www.youtube.com/playlist?list=PLg5d1Q7lsu5EotIPJoe-Y0x7u32ivDMDi",
        color: "#e83e8c",
        icon: faIcons,
      },
      {
        id: 3724,
        name: "Indian Children Songs",
        url: "https://open.spotify.com/playlist/3UJut4tjr8GD7dMZeP1Cs7",
        color: "#343a40",
        icon: faGuitar,
      },
      {
        id: 3721,
        name: "Music & Dance for Kids",
        url: "https://www.splashlearn.com/blog/the-complete-playlist-of-dance-songs-for-kids-to-get-them-grooving/",
        color: "#20c997",
        icon: faChildReaching,
      },
      {
        id: 3718,
        name: "Creativity & Performing Arts",
        url: "https://parents.highlights.com/31-arts-and-crafts-kids-to-make-home",
        color: "#007bff",
        icon: faDemocrat,
      },
      {
        id: 3698,
        name: "Creativity & Performing Arts",
        url: "https://www.pinterest.com/kbkonnected/art-and-crafts-for-kids/",
        color: "#dc3545",
        icon: faNewspaper,
      },
      {
        id: 3691,
        name: "Creativity & Performing Arts",
        url: "https://www.alldayprimary.com/arts-and-crafts",
        color: "#28a745",
        icon: faMasksTheater,
      },
    ],
  },
  {
    title: "Academic Learning",
    resources: [
      {
        id: 3690,
        name: "Animated Learning Videos",
        url: "https://www.fiverr.com/categories/video-animation/animation-for-kids",
        color: "#007bff",
        icon: faFileVideo,
      },
      {
        id: 3689,
        name: "Animated Learning Videos",
        url: "https://flearningstudio.com/top-animated-educational-videos/",
        color: "#dc3545",
        icon: faVideo,
      },
      {
        id: 3688,
        name: "Learning English & Phonics",
        url: "https://www.kizphonics.com/",
        color: "#28a745",
        icon: faLinesLeaning,
      },
      {
        id: 3687,
        name: "Language & Communication ● Reading Aloud & Storytelling",
        url: "https://www.splashlearn.com/blog/how-to-teach-phonics-to-kids/",
        color: "#ffc107",
        icon: faChalkboardUser,
      },
      {
        id: 3684,
        name: "Learning English & Phonics",
        url: "https://www.socratica.org/courses/the-alphabet-a-z?gad_source=1&gclid=CjwKCAiAzba9BhBhEiwA7glbamCbFsOEgRmn5nlA5GG9oyVaxesPS_2_E2NTXPXEpMUDaX3R4-1yIRoCPIgQAvD_BwE",
        color: "#fd7e14",
        icon: faBookOpen,
      },
      {
        id: 3681,
        name: "Learning English & Phonics",
        url: "https://advancedlearning.com.sg/the-best-8-phonics-learning-method-for-primary-school-kids/",
        color: "#6f42c1",
        icon: faBookOpenReader,
      },
      {
        id: 3679,
        name: "Introduction to Social Studies & Indian Culture",
        url: "https://www.twinkl.co.in/teaching-wiki/social-studies",
        color: "#17a2b8",
        icon: faBookAtlas,
      },
      {
        id: 3675,
        name: "Science Experiments for Kids",
        url: "https://www.splashlearn.com/blog/kids-science-experiments-to-make-learning-engaging/",
        color: "#e83e8c",
        icon: faAppleWhole,
      },
      {
        id: 3674,
        name: "Science Experiments for Kids",
        url: "https://www.goodhousekeeping.com/life/parenting/g32176446/science-experiments-for-kids/",
        color: "#343a40",
        icon: faAtom,
      },
      {
        id: 3673,
        name: "Science Experiments for Kids",
        url: "https://www.sciencefun.org/kidszone/experiments/top-science-experiments-for-kids/",
        color: "#20c997",
        icon: faMicroscope,
      },
      {
        id: 3671,
        name: "Picture Books",
        url: "https://www.storyberries.com/category/picture-books/",
        color: "#007bff",
        icon: faBook,
      },
      {
        id: 3670,
        name: "Fun with Numbers & Basic Math",
        url: "https://www.mathplayground.com/math-games.html",
        color: "#dc3545",
        icon: faBook,
      },
      {
        id: 3669,
        name: "Fun with Numbers & Basic Math",
        url: "https://www.mathsisfun.com/",
        color: "#28a745",
        icon: faBookBible,
      },
      {
        id: 3668,
        name: "Fun with Numbers & Basic Math",
        url: "https://www.mathgames.com/",
        color: "#ffc107",
        icon: faBookBible,
      },
      {
        id: 3667,
        name: "Storybooks & Picture Books",
        url: "https://monkeypen.com/pages/free-childrens-books",
        color: "#fd7e14",
        icon: faBookTanakh,
      },
      {
        id: 3666,
        name: "Picture & Story Books",
        url: "https://www.spellboundbookstore.com/collections/picture-books-1/picture-books",
        color: "#6f42c1",
        icon: faStore,
      },
      {
        id: 3665,
        name: "Storybooks & Picture Books",
        url: "http://letsreadasia.org/",
        color: "#17a2b8",
        icon: faBookJournalWhills,
      },
    ],
  },
  {
    title: "Environment & Social Responsibility",
    resources: [
      {
        id: 3739,
        name: "Teaching waste management to children",
        url: "https://www.smilefoundationindia.org/blog/teaching-waste-management-to-children/",
        color: "#007bff",
        icon: faHandsHoldingChild,
      },
      {
        id: 3737,
        name: "Reduce, Reuse, Recycle",
        url: "https://kids.niehs.nih.gov/topics/reduce",
        color: "#dc3545",
        icon: faRecycle,
      },
      {
        id: 3735,
        name: "Recycling & Waste Management for Kids",
        url: "https://www.iberdrola.com/sustainability/recycling-for-kids",
        color: "#28a745",
        icon: faRecycle,
      },
      {
        id: 3733,
        name: "Things Children Learn From Playing With Animals",
        url: "https://kerensnursery.com/8-things-children-learn-from-playing-with-animals/",
        color: "#ffc107",
        icon: faCat,
      },
      {
        id: 3731,
        name: "Zoos neither educate nor empower children",
        url: "https://www.freedomforanimals.org.uk/news/zoos-neither-educate-nor-empower-children",
        color: "#fd7e14",
        icon: faOtter,
      },
      {
        id: 3729,
        name: "Tips for Teaching Wildlife Conservation for Kids",
        url: "https://environment.co/tips-for-teaching-wildlife-conservation-for-kids/",
        color: "#6f42c1",
        icon: faHippo,
      },
      {
        id: 3728,
        name: "Learning about Animals & Conservation",
        url: "https://www.lego.com/en-in/themes/duplo/article/teaching-animal-conservation",
        color: "#17a2b8",
        icon: faHorse,
      },
      {
        id: 3726,
        name: "Garden With Kids: Fun Activities",
        url: "https://www.almanac.com/gardening-kids-what-plant-and-fun-activities",
        color: "#e83e8c",
        icon: faLeaf,
      },
      {
        id: 3723,
        name: "Childrens Garden Fun",
        url: "https://www.coordikids.com/childrens-garden-fun/",
        color: "#343a40",
        icon: faMountainCity,
      },
      {
        id: 3722,
        name: "Fun Winter Garden Activities for Kids",
        url: "https://www.gardenary.com/blog/fun-winter-garden-activities-for-kids",
        color: "#20c997",
        icon: faMountainSun,
      },
      {
        id: 3720,
        name: "Fun Garden Activities for Kids",
        url: "https://kidsgardening.org/resource-activities/",
        color: "#007bff",
        icon: faPlantWilt,
      },
      {
        id: 3719,
        name: "Fun with Nature & Gardening",
        url: "http://kangarookids.in/blog/gardening-activities-and-nature-exploration-for-preschoolers/",
        color: "#dc3545",
        icon: faTree,
      },
    ],
  },
  {
    title: "Health & Well-being",
    resources: [
      {
        id: 3717,
        name: "Basic First Aid Awareness",
        url: "Basic First Aid Awareness",
        color: "#007bff",
        icon: faStarOfLife,
      },
      {
        id: 3716,
        name: "Basic First Aid Awareness",
        url: "https://kidsage.in/10-ways-to-teach-children-about-basic-first-aid/",
        color: "#dc3545",
        icon: faBriefcaseMedical,
      },
      {
        id: 3715,
        name: "Emotional Well-being & Kindness",
        url: "https://ripplekindness.org/mindfulness-enhances-kindness-wellbeing-in-kids/",
        color: "#28a745",
        icon: faFaceSmile,
      },
      {
        id: 3714,
        name: "Emotional Well-being & Kindness",
        url: "Emotional Well-being & Kindness",
        color: "#ffc107",
        icon: faHeart,
      },
      {
        id: 3711,
        name: "Emotional Well-being & Kindness",
        url: "https://www.premier-education.com/news/5-ways-to-encourage-emotional-wellbeing-for-children/",
        color: "#fd7e14",
        icon: faHeadSideMask,
      },
      {
        id: 3704,
        name: "Healthy Eating & Hygiene Habits",
        url: "https://health.clevelandclinic.org/healthy-eating-for-kids",
        color: "#6f42c1",
        icon: faUtensils,
      },
      {
        id: 3701,
        name: "Healthy Eating & Hygiene Habits",
        url: "https://www.healthdirect.gov.au/personal-hygiene-for-children",
        color: "#17a2b8",
        icon: faHandsBubbles,
      },
      {
        id: 3700,
        name: "Healthy Eating & Hygiene Habits",
        url: "https://kidshealth.org/en/parents/habits.html",
        color: "#e83e8c",
        icon: faBowlFood,
      },
      {
        id: 3697,
        name: "Fun Exercises & Yoga for Kids",
        url: "https://www.arhantayoga.org/blog/yoga-poses-for-kids/",
        color: "#343a40",
        icon: faPersonWalking,
      },
      {
        id: 3696,
        name: "Fun Exercises & Yoga for Kids",
        url: "https://www.kidsyogastories.com/kids-yoga-poses/",
        color: "#20c997",
        icon: faDumbbell,
      },
      {
        id: 3695,
        name: "Fun Exercises & Yoga for Kids",
        url: "https://kumarahyoga.com/5-active-kids-yoga-games-to-have-fun-in-a-group/?srsltid=AfmBOorsfrwQBY9rW09ykz14udEUe5HsdT6nCb-zvRMdUa9z9Xg_65KN",
        color: "#007bff",
        icon: faPersonWalking,
      },
    ],
  },
];

function PrimaryPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      {/* HEADER PART */}
      <h1 className="text-3xl font-bold text-center my-6">Primary</h1>

      {data.map((section, index) => (
        <div key={index} className="mb-10 ">
          <h2 className="text-2xl font-semibold mb-4">{section.title}</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {section.resources.map(({ icon, color, name, url }, idx) => (
              <ResourceCardFortAwesome
                key={idx}
                icon={icon}
                color={color}
                name={name}
                url={url}
              />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

export default PrimaryPage;
