export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export   const bgColors = [
  "bg-gradient-to-r from-blue-600 to-indigo-600",
  "bg-gradient-to-r from-green-500 to-emerald-600",
  "bg-gradient-to-r from-red-500 to-pink-600",
  "bg-gradient-to-r from-purple-500 to-fuchsia-600",
  "bg-gradient-to-r from-pink-500 to-rose-600",
  "bg-gradient-to-r from-yellow-500 to-amber-600",
  "bg-gradient-to-r from-indigo-500 to-violet-600",
  "bg-gradient-to-r from-cyan-500 to-sky-600",
  "bg-gradient-to-r from-teal-500 to-emerald-600",
  "bg-gradient-to-r from-orange-500 to-red-600",
  "bg-gradient-to-r from-rose-500 to-pink-600",
  "bg-gradient-to-r from-fuchsia-500 to-pink-600",
  "bg-gradient-to-r from-violet-500 to-purple-600",
  "bg-gradient-to-r from-lime-500 to-green-600",
  "bg-gradient-to-r from-emerald-500 to-teal-600",
  "bg-gradient-to-r from-amber-500 to-orange-600",
  "bg-gradient-to-r from-sky-500 to-cyan-600",
  "bg-gradient-to-r from-slate-600 to-slate-800",
  "bg-gradient-to-r from-zinc-600 to-zinc-800",
  "bg-gradient-to-r from-neutral-600 to-neutral-800",
];