"use client";
import React, from "react";
import {
  faMasksTheater,
  faUserDoctor,
  faNotesMedical,
  faHeart,
  faBrain,
  faDumbbell,
  faMicrophone,
  faMusic,
  faCirclePlay,
  faVideo,
  faPodcast,
  faBriefcase,
  faClipboardList,
  faLightbulb,
  faChartLine,
  faGlobe,
  faSquarePen,
  faChalkboard,
  faPen,
  faUserGraduate,
  faVialCircleCheck,
  faRadiation,
  faBookOpenReader,
  faBookTanakh,
  faPersonSnowboarding,
  faSchool,
  faBookOpen,
  faBook,
  faLaptopFile,
  faLinesLeaning,
  faLandmark,
  faComments,
  faBuildingColumns,
  faVrCardboard,
  faGopuram,
  faFilm,
  faDice,
  faPuzzlePiece,
  faTabletButton,
  faTabletScreenButton,
  faPenClip,
  faPenRuler,
  faFilePen,
  faTachographDigital,
  faBuildingLock,
  faUserClock,
  faUserLock,
  faLock,
  faChalkboardUser,
  faRobot,
  faPlus,
  faBullseye,
  faCoins,
  faClock,
  faPeopleGroup,
  faHandshakeAngle,
  faPlateWheat,
  faUsers,
  faUser,
  faGavel,
  faSeedling,
  faGraduationCap,
} from "@fortawesome/free-solid-svg-icons";
import { faArtstation, faLeanpub } from "@fortawesome/free-brands-svg-icons";
import {
  faLanguage,
  faPersonChalkboard,
  faUserTie,
} from "@fortawesome/free-solid-svg-icons";
import { ResourceCardFortAwesome } from "@/components";
import { faFigma } from "@fortawesome/free-brands-svg-icons"; 

const data = [
  {
    title: "Life Skills & Personal Development",
    resources: [
      {
        id: 3963,
        name: "Goal Setting for Students: A Step-by-Step Guide",
        url: "https://www.oxfordscholastica.com/blog/goal-setting-for-students-a-step-by-step-guide/",
        icon: faBullseye,
        color: "#007bff",
      },
      {
        id: 3962,
        name: "Motivation and Goal Setting",
        url: "https://www.cuesta.edu/student/resources/ssc/study_guides/study_skills/502_study_goals.html",
        icon: faBullseye,
        color: "#dc3545",
      },
      {
        id: 3961,
        name: "Decision Making and Goal Setting",
        url: "https://careers.umbc.edu/students/discover/goals/",
        icon: faBullseye,
        color: "#28a745",
      },
      {
        id: 3957,
        name: "The Empowering Effect Of Personal Finance Education On High School Students",
        url: "https://futureeducationmagazine.com/impact-of-personal-finance-education/",
        icon: faCoins,
        color: "#ffc107",
      },
      {
        id: 3954,
        name: "School of Finance: 7 Essential Tips for High School Students",
        url: "https://www.penncommunitybank.com/blog/school-of-finance-7-essential-tips-for-high-school-students/",
        icon: faCoins,
        color: "#fd7e14",
      },
      {
        id: 3952,
        name: "Guide to Personal Finance for High School Students",
        url: "https://www.aralia.com/helpful-information/personal-finance-high-school/",
        icon: faCoins,
        color: "#6f42c1",
      },
      {
        id: 3946,
        name: "Time Management: 15 Tips for Middle and High School Students",
        url: "https://kdcollegeprep.com/time-management-15-tips-for-middle-and-high-school-students/",
        icon: faClock,
        color: "#17a2b8",
      },
      {
        id: 3944,
        name: "How to Improve Time Management for Students and Reduce Stress",
        url: "https://setmycareer.com/blog/how-to-improve-time-management-for-students.php",
        icon: faClock,
        color: "#e83e8c",
      },
      {
        id: 3943,
        name: "Complete Guide to Stress and Time Management for Students",
        url: "https://www.uwslondon.ac.uk/complete-guide-to-stress-management-and-time-management-for-students/",
        icon: faClock,
        color: "#343a40",
      },
      // {
      //   id: 3927,
      //   name: "Nature of teamwork and different types of Leadership styles",
      //   url: "https://learn.saylor.org/mod/page/view.php?id=51222",
      //   icon: faPeopleGroup,
      //   color: "#20c997",
      // },
      {
        id: 3926,
        name: "Teamwork and Leadership",
        url: "https://ecampusontario.pressbooks.pub/commbusprofcdn/chapter/teamwork-and-leadership/",
        icon: faPeopleGroup,
        color: "#007bff",
      },
      {
        id: 3925,
        name: "Leadership and teamwork: 10 ways leaders can help their teams",
        url: "https://www.teamwork.com/blog/10-ways-leaders-teams/",
        icon: faPeopleGroup,
        color: "#dc3545",
      },
    ],
  },
  {
    title: "Fun Edutainment",
    resources: [
      {
        id: 3989,
        name: "Analyzing augmented reality (AR) and virtual reality (VR) recent development in education",
        url: "https://www.sciencedirect.com/science/article/pii/S2590291123001377",
        icon: faVrCardboard,
        color: "#007bff",
      },
      {
        id: 3988,
        name: "Virtual Reality in Education: Benefits, Tools, and Resources",
        url: "https://soeonline.american.edu/blog/benefits-of-virtual-reality-in-education/",
        icon: faVrCardboard,
        color: "#dc3545",
      },
      {
        id: 3987,
        name: "Virtual Reality in Education",
        url: "https://www.classvr.com/virtual-reality-in-education/",
        icon: faVrCardboard,
        color: "#28a745",
      },
      {
        id: 3986,
        name: "Indian & World Mythology",
        url: "https://www.originaltravel.co.uk/travel-blog/an-introduction-to-myths-and-legends-in-india",
        icon: faGopuram,
        color: "#ffc107",
      },
      {
        id: 3985,
        name: "Indian & Hindu Mythology | Avatars, Stories & Gods",
        url: "https://study.com/academy/lesson/gods-stories-from-indian-mythology.html#:~:text=Trimurti%20is%20a%20triune%20deity,knowledge%2C%20and%20the%20vedic%20texts.",
        icon: faGopuram,
        color: "#fd7e14",
      },
      {
        id: 3984,
        name: "8 Mind-Blowing Space Documentaries to Watch Now on NOVA",
        url: "https://www.pbs.org/wgbh/nova/article/best-space-documentaries-streaming/",
        icon: faFilm,
        color: "#6f42c1",
      },
      {
        id: 3983,
        name: "15 Great Documentary Movies for Middle and High School Classrooms",
        url: "https://www.commonsense.org/education/articles/15-great-documentary-movies-for-middle-and-high-school-classrooms",
        icon: faFilm,
        color: "#17a2b8",
      },
      {
        id: 3982,
        name: "Escape Room Challenge: Minecraft! Logic, Puzzles, Trivia & Riddles",
        url: "https://outschool.com/classes/escape-room-challenge-minecraft-logic-puzzles-trivia-riddles-ages-10-14-YzHNvm3X?srsltid=AfmBOooeMjIny5x_7_5seqSe8BIeibNWA3uc05t_U5IZ-No_oKxd7fdB",
        icon: faDice,
        color: "#e83e8c",
      },
      {
        id: 3981,
        name: "20 Best Math Puzzles to Engage and Challenge Your Students",
        url: "https://www.prodigygame.com/main-en/blog/math-puzzles/",
        icon: faPuzzlePiece,
        color: "#343a40",
      },
      {
        id: 3980,
        name: "Logical Puzzles & Escape Room Challenges",
        url: "https://learninghypothesis.com/escape-room-puzzle-ideas/",
        icon: faPuzzlePiece,
        color: "#20c997",
      },
    ],
  },
  {
    title: "Academic Learning",
    resources: [
      {
        id: 3896,
        name: "Academic Writing Style",
        url: "https://library.sacredheart.edu/c.php?g=29803&p=185910",
        icon: faSquarePen,
        color: "#007bff",
      },
      {
        id: 3895,
        name: "Research & Academic Writing",
        url: "https://www.indeed.com/career-advice/career-development/academic-writing",
        icon: faChalkboard,
        color: "#dc3545",
      },
      {
        id: 3893,
        name: "Academic Research Writing",
        url: "https://quillbot.com/courses/research-based-writing/chapter/academic-research-writing-what-is-it/",
        icon: faPen,
        color: "#28a745",
      },
      {
        id: 3886,
        name: "Students Engineering Projects",
        url: "https://sciencefaircentral.com/students/engineering-projects",
        icon: faUserGraduate,
        color: "#ffc107",
      },
      {
        id: 3884,
        name: "Science Projects",
        url: "https://www.sciencebuddies.org/science-fair-projects/science-projects",
        icon: faVialCircleCheck,
        color: "#fd7e14",
      },
      {
        id: 3883,
        name: "Science & Engineering Projects",
        url: "https://www.sciencebuddies.org/science-fair-projects/landing-engineering.shtml",
        icon: faRadiation,
        color: "#6f42c1",
      },
      // {
      //   id: 3882,
      //   name: "How the SCORE Scholarship Can Help You Prepare JEE, NEET, CUET, Olympiads",
      //   url: "https://infinitylearn.com/blog/how-the-score-scholarship-can-help-you-prepare-jee-neet-cuet-olympiads",
      //   icon: faBookOpenReader,
      //   color: "#17a2b8",
      // },
      {
        id: 3880,
        name: "Early Starters A Guide To JEE, NEET And Olympiad Preparation",
        url: "https://sathee.prutor.ai/article/engineering/early_starters_a_guide_to_jeeneet_and_olympiad_preparation/",
        icon: faBookTanakh,
        color: "#e83e8c",
      },
      {
        id: 3878,
        name: "How to Prepare for Olympiad Exams",
        url: "https://margshree.com/blog/how-to-prepare-for-olympiad-exams/",
        icon: faPersonSnowboarding,
        color: "#343a40",
      },
      {
        id: 3876,
        name: "Competitive Exam Prep",
        url: "https://genesisclasses.net/neet/index.php",
        icon: faSchool,
        color: "#20c997",
      },
      {
        id: 3875,
        name: "All-State Board Books",
        url: "https://www.selfstudys.com/page/state-board-books",
        icon: faBookOpen,
        color: "#007bff",
      },
      {
        id: 3872,
        name: "NCERT, State Boards, Reference Books",
        url: "https://ncert.nic.in/textbook.php",
        icon: faBook,
        color: "#dc3545",
      },
      {
        id: 3871,
        name: "Advanced-placement-courses",
        url: "https://courseleap.org/advanced-placement-courses/",
        icon: faLaptopFile,
        color: "#28a745",
      },
      {
        id: 3868,
        name: "Advanced Topics",
        url: "https://brilliant.org/paths/advanced-and-applied-science/",
        icon: faLightbulb,
        color: "#ffc107",
      },
      {
        id: 3867,
        name: "Advanced Learning",
        url: "https://www.frontiersin.org/research-topics/8563/advanced-learning",
        icon: faLinesLeaning,
        color: "#fd7e14",
      },
      {
        id: 3866,
        name: "Advanced Learners",
        url: "https://cty.jhu.edu/resources-support-advanced-learners/advanced-learners-101",
        icon: faLeanpub,
        color: "#6f42c1",
      },
      {
        id: 3864,
        name: "Explore the STEM Course Catalog",
        url: "https://www.coursera.org/courses?query=stem",
        icon: faLandmark,
        color: "#17a2b8",
      },
      {
        id: 3861,
        name: "Advanced Subject Learning (STEM, Humanities, Commerce)",
        url: "Advanced Subject Learning (STEM, Humanities, Commerce)",
        icon: faBuildingColumns,
        color: "#e83e8c",
      },
    ],
  },
  {
    title: "Career Awareness & Future Readiness",
    resources: [
      {
        id: 4001,
        name: "College Admissions: Your Step-by-Step Guide",
        url: "https://www.listening.com/blog/college-admissions/",
        icon: faBuildingColumns,
        color: "#007bff",
      },
      {
        id: 3999,
        name: "National Scholarships",
        url: "https://www.education.gov.in/scholarships-education-loan-0",
        icon: faGraduationCap,
        color: "#dc3545",
      },
      {
        id: 3998,
        name: "Comprehensive Scholarship Guide",
        url: "https://study.com/resources/college-scholarships-guide",
        icon: faGraduationCap,
        color: "#28a745",
      },
      {
        id: 3997,
        name: "Workplace Etiquette: 21 Dos and Don’ts of the Workplace",
        url: "https://graduate.northeastern.edu/knowledge-hub/workplace-etiquette/",
        icon: faPenRuler,
        color: "#ffc107",
      },
      {
        id: 3996,
        name: "Soft skills 101: definition + 50 examples",
        url: "https://joinhandshake.com/blog/students/soft-skills-examples/",
        icon: faPen,
        color: "#fd7e14",
      },
      {
        id: 3995,
        name: "Soft Skills & Workplace Etiquette",
        url: "https://www.europeanfinancialreview.com/soft-skills-and-effective-corporate-etiquette/",
        icon: faBook,
        color: "#6f42c1",
      },
      {
        id: 3994,
        name: "Mentor-Intern Program",
        url: "https://www.globalcitizenshipfoundation.org/internships",
        icon: faLinesLeaning,
        color: "#17a2b8",
      },
      {
        id: 3993,
        name: "Intern Mentoring Program: Building a Better Future Together",
        url: "https://www.qooper.io/blog/intern-mentoring-program-building-a-better-future-together",
        icon: faLinesLeaning,
        color: "#e83e8c",
      },
      {
        id: 3992,
        name: "Internship & Mentorship Programs",
        url: "https://ic3institute.org/volunteering/",
        icon: faLinesLeaning,
        color: "#343a40",
      },
      {
        id: 3991,
        name: "STEM Education in High Schools: College and Career Preparation",
        url: "https://www.vikasconcept.com/stem-education-in-high-schools-college-and-career-preparation/",
        icon: faSchool,
        color: "#20c997",
      },
      {
        id: 3990,
        name: "Career Exploration (STEM, Arts, Entrepreneurship)",
        url: "https://blog.definedlearning.com/blog/early-stem-career-exploration",
        icon: faArtstation,
        color: "#007bff",
      },
    ],
  },
  {
    title: "Digital Literacy & Tech Skills",
    resources: [
      {
        id: 3929,
        name: "Best Web-Design Apps and Websites for Students",
        url: "https://www.commonsense.org/education/lists/best-web-design-apps-and-websites-for-students",
        icon: faTabletButton,
        color: "#007bff",
      },
      {
        id: 3928,
        name: "App Development & Web Designing",
        url: "https://www.designstudiouiux.com/web-design-agency/?gad_source=1&gclid=EAIaIQobChMIrL-s1MPbiwMVZvU8Ah0J3Q0-EAAYAiAAEgJX1_D_BwE",
        icon: faTabletScreenButton,
        color: "#dc3545",
      },
      {
        id: 3911,
        name: "Digital Content Types: How To Create Digital Content",
        url: "https://www.shopify.com/blog/digital-content",
        icon: faPenClip,
        color: "#28a745",
      },
      {
        id: 3909,
        name: "Digital Content Creation",
        url: "https://ahrefs.com/blog/digital-content-creation/",
        icon: faPenRuler,
        color: "#ffc107",
      },
      {
        id: 3908,
        name: "Digital Content",
        url: "https://www.semrush.com/blog/digital-content-creation/",
        icon: faFilePen,
        color: "#fd7e14",
      },
      {
        id: 3906,
        name: "Digital Content Creation & Blogging",
        url: "https://www.creativepossibilityproject.com/chatgpt-course?gad_source=1&gclid=CjwKCAiA8Lu9BhA8EiwAag16b0Ibdh-V1x4AbFbCEzraPzBkBHDcLLlQFupcsYLIFP1zbE_UnBTOGxoCOTAQAvD_BwE",
        icon: faTachographDigital,
        color: "#6f42c1",
      },
      {
        id: 3905,
        name: "Ethical Issues Related to Data Privacy and Security",
        url: "https://digitalprivacy.ieee.org/publications/topics/ethical-issues-related-to-data-privacy-and-security-why-we-must-balance-ethical-and-legal-requirements-in-the-connected-world",
        icon: faBuildingLock,
        color: "#17a2b8",
      },
      {
        id: 3903,
        name: "Privacy in computer ethics: Navigating the digital age",
        url: "https://www.researchgate.net/publication/371981101_Privacy_in_computer_ethics_Navigating_the_digital_age",
        icon: faUserClock,
        color: "#e83e8c",
      },
      {
        id: 3902,
        name: "Cyber Ethics",
        url: "https://www.gov.hk/en/residents/communication/infosec/guidelines/cyberethics.htm",
        icon: faUserLock,
        color: "#343a40",
      },
      // {
      //   id: 3901,
      //   name: "Cyber Ethics & Online Privacy",
      //   url: "https://password-saver.com/data-leakage-protection/?utm_source=google&utm_medium=cpc&utm_campaign=inweb_SER_password-saver_Statti_India&utm_content=582253304639&utm_term=cyber%20security%20and%20data%20protection&gad_source=1&gclid=CjwKCAiA8Lu9BhA8EiwAag16b66aBFdA9LmLyR45LmeHQnUeCtuFcuq75evr0bs8nI3rYQREQK0CWxoCxcsQAvD_BwE",
      //   icon: faLock,
      //   color: "#20c997",
      // },
      {
        id: 3899,
        name: "Become an Expert in Machine Learning & AI with IIIT-B",
        url: "https://www.upgrad.com/machine-learning-ai-pgd-iiitb-lpv1/?utm_source=GOOGLE&utm_medium=NBSEARCH&utm_campaign=IND_ACQ_WEB_GOOGLE_NBSEARCH_DV_IIITB_EML_HIT_T1_DAcc&utm_content=AI_ML_Courses&utm_term=learn%20ai%20and%20machine%20learning&ad_device=c&ad_network=g&ad_creative=647075414140&ad_placement=&ad_keyword_matchtype=p&ad_clickid=CjwKCAiA8Lu9BhA8EiwAag16b5jI2N0LbztcqOiUbe_57jPDgYA7vsYHHsCfyXgMsgo6znW50tKieBoCWMAQAvD_BwE",
        icon: faLaptopFile,
        color: "#007bff",
      },
      {
        id: 3898,
        name: "Machine Learning",
        url: "https://in.mathworks.com/solutions/machine-learning.html?gclid=CjwKCAiA8Lu9BhA8EiwAag16b-tdUdeQ1xRS5Q9xYxyKa_JCvEWqBSQk0Z62ZNLw3yo3w_77h1wheBoCbSEQAvD_BwE&ef_id=CjwKCAiA8Lu9BhA8EiwAag16b-tdUdeQ1xRS5Q9xYxyKa_JCvEWqBSQk0Z62ZNLw3yo3w_77h1wheBoCbSEQAvD_BwE%3AG%3As&s_kwcid=AL!8664!3!604541475536!p!!g!!machine+learning&s_eid=psn_57384022552&q=machine+learning&gad_source=1",
        icon: faChalkboardUser,
        color: "#dc3545",
      },
      {
        id: 3897,
        name: "Competing in the Age of AI",
        url: "https://www.exed.hbs.edu/competing-age-ai?utm_source=google&utm_medium=paid-search&utm_campaign=non-brand-program-aiv-global-none-phrase-cross-device-all&utm_id=core&gad_source=1&gclid=CjwKCAiA8Lu9BhA8EiwAag16b-eXR6r8jsqpNhM3czNFfMrTIi5cK_hBuKwU7-dZhccJ2HwNvcmYhBoCWQsQAvD_BwE&gclsrc=aw.ds",
        icon: faRobot,
        color: "#28a745",
      },
    ],
  },
  {
    title: "Language & Communication",
    resources: [
      {
        id: 3924,
        name: "10 Ways that Participating in a MUN Can Help You in the Future",
        url: "https://www.mindler.com/blog/advantages-and-benefits-of-mun/",
        icon: faComments,
        color: "#007bff",
      },
      {
        id: 3923,
        name: "Practicing Debate",
        url: "https://foundation.thimun.org/wp-content/uploads/2023/08/Booklet-9-Practicing-Debate.pdf",
        icon: faComments,
        color: "#dc3545",
      },
      {
        id: 3922,
        name: "Model United Nations and Debate",
        url: "https://bestdelegate.com/model-united-nations-and-debate/",
        icon: faComments,
        color: "#28a745",
      },
      // {
      //   id: 3921,
      //   name: "How Learning a Foreign Language Can Boost Your Career",
      //   url: "https://sunbeamworldschool.com/blog/how-learning-a-foreign-language-can-boost-your-career/",
      //   icon: faLanguage,
      //   color: "#ffc107",
      // },
      {
        id: 3920,
        name: "15 Evergreen Careers for Language Enthusiasts: Skills, Courses, Exams & Career Scope",
        url: "https://www.mindler.com/blog/15-evergreen-careers-for-language-enthusiasts-skills-courses-exams-career-scope/",
        icon: faLanguage,
        color: "#fd7e14",
      },
      {
        id: 3919,
        name: "The 12 Most Important Languages To Learn For Success",
        url: "https://www.uopeople.edu/blog/most-important-languages-to-learn/",
        icon: faLanguage,
        color: "#6f42c1",
      },
      {
        id: 3918,
        name: "Presentation Skills - 16 Tips for Effective Presentations",
        url: "https://www.cbs.de/en/blog/15-effective-presentation-tips-to-improve-presentation-skills/",
        icon: faPersonChalkboard,
        color: "#17a2b8",
      },
      {
        id: 3917,
        name: "Public Speaking And Presentation Skills: All You Need To Know!",
        url: "https://kapable.club/blog/public-speaking/public-speaking-and-presentation-skills-all-you-need-to-know/",
        icon: faPersonChalkboard,
        color: "#e83e8c",
      },
      {
        id: 3916,
        name: "What Are Effective Presentation Skills",
        url: "https://www.coursera.org/in/articles/presentation-skills",
        icon: faPersonChalkboard,
        color: "#343a40",
      },
      {
        id: 3915,
        name: "High School Student Resume Examples & Writing Guide for 2025",
        url: "https://www.kickresume.com/en/help-center/high-school-student-resume-samples/",
        icon: faUserTie,
        color: "#20c997",
      },
      {
        id: 3914,
        name: "High School Student Resume Examples And Tips",
        url: "https://in.indeed.com/career-advice/resumes-cover-letters/high-school-student-resume-examples",
        icon: faUserTie,
        color: "#007bff",
      },
      {
        id: 3913,
        name: "6 High School Resume Examples and Templates for 2025",
        url: "https://www.resumebuilder.com/resume-examples/high-school-students/",
        icon: faUserTie,
        color: "#dc3545",
      },
    ],
  },
  {
    title: "Environment & Social Responsibility",
    resources: [
      {
        id: 3979,
        name: "Volunteers Stakeholder Group",
        url: "https://sustainabledevelopment.un.org/index.php?page=view&type=30022&nr=2914&menu=3170",
        icon: faHandshakeAngle,
        color: "#007bff",
      },
      {
        id: 3978,
        name: "Sustainable Development Goals",
        url: "https://www.unv.org/volunteerism-and-global-goals",
        icon: faHandshakeAngle,
        color: "#dc3545",
      },
      // {
      //   id: 3977,
      //   name: "How can I volunteer for the SDGs",
      //   url: "https://sdgzone.com/action/how-can-i-volunteer/",
      //   icon: faHandshakeAngle,
      //   color: "#28a745",
      // },
      {
        id: 3976,
        name: "Action Against Hunger: Advancing India’s Sustainable Development Goals",
        url: "https://actionagainsthunger.in/action-against-hunger-advancing-indias-sustainable-development-goals",
        icon: faPlateWheat,
        color: "#ffc107",
      },
      {
        id: 3975,
        name: "Entrepreneurship Competitions for High School Students",
        url: "https://www.polygence.org/blog/entrepreneurship-competitions-for-high-school-students",
        icon: faUsers,
        color: "#fd7e14",
      },
      {
        id: 3974,
        name: "Social Innovation | Social Entrepreneurship",
        url: "https://impactgarden.org/social-innovation/",
        icon: faLightbulb,
        color: "#6f42c1",
      },
      // {
      //   id: 3973,
      //   name: "Entrepreneurship & Social Innovation",
      //   url: "https://www.alfanar.org/intro-to-socent",
      //   icon: faUser,
      //   color: "#17a2b8",
      // },
      {
        id: 3972,
        name: "National Centre for Good Governance",
        url: "https://ncgg.org.in/training/",
        icon: faGavel,
        color: "#e83e8c",
      },
      {
        id: 3971,
        name: "Policy and governance in education: Shaping effective leadership",
        url: "https://educationonline.ku.edu/community/policy-and-governance-in-education",
        icon: faGavel,
        color: "#343a40",
      },
      {
        id: 3970,
        name: "Policy & Governance Awareness",
        url: "https://www.isdm.org.in/governance",
        icon: faSeedling,
        color: "#20c997",
      },
    ],
  },
  {
    title: "Creativity & Performing Arts",
    resources: [
      {
        id: 3956,
        name: "Advanced Drama/IB Theatre",
        url: "https://dbhs.wvusd.org/apps/pages/index.jsp?uREC_ID=1005306&type=u&pREC_ID=1479650",
        icon: faMasksTheater,
        color: "#007bff",
      },
      {
        id: 3955,
        name: "Theatre High School Advanced Acting",
        url: "https://www.nationalartsstandards.org/content/theatre-high-school-advanced-acting-student-work",
        icon: faMasksTheater,
        color: "#dc3545",
      },
      {
        id: 3953,
        name: "Advanced drama and theatre studies",
        url: "https://example.com", // Replace with correct URL
        icon: faMasksTheater,
        color: "#28a745",
      },
      {
        id: 3951,
        name: "Audio Academy",
        url: "https://audioacademy.in/",
        icon: faMicrophone,
        color: "#ffc107",
      },
      {
        id: 3950,
        name: "Music Production and Sound Engineering Institutes in India",
        url: "https://www.tgcindia.com/top-10-music-production-and-sound-engineering-institutes-in-india/",
        icon: faMusic,
        color: "#fd7e14",
      },
      {
        id: 3949,
        name: "Music production workshops",
        url: "https://www.campfr.com/?gad_source=1&gclid=EAIaIQobChMI05GT8dPbiwMV96dmAh1gwwoqEAAYASAAEgKNIfD_BwE",
        icon: faMusic,
        color: "#6f42c1",
      },
      {
        id: 3948,
        name: "Best Podcast Apps and Websites for Students",
        url: "https://www.commonsense.org/education/lists/best-podcast-apps-and-websites-for-students",
        icon: faCirclePlay,
        color: "#17a2b8",
      },
      {
        id: 3947,
        name: "Video - Podcast",
        url: "https://www.podcastingsmart.com/editlab",
        icon: faVideo,
        color: "#e83e8c",
      },
      {
        id: 3945,
        name: "Podcast Editing: How to Do It In 11 Steps",
        url: "https://riverside.fm/blog/podcast-editing",
        icon: faPodcast,
        color: "#343a40",
      },
      {
        id: 3942,
        name: "Graphic Design and Animation",
        url: "https://www.dreamzone.co.in/graphics-design-certification-training/",
        icon: faMasksTheater,
        color: "#20c997",
      },
      // {
      //   id: 3941,
      //   name: "Graphic Design & Animation",
      //   url: "https://ads.idea-worldwide.com/?utm_source=&utm_campaign=&utm_ad_group=&utm_keyword=schooling%20for%20graphic%20design&gad_source=1&gclid=EAIaIQobChMI9a6O_9HbiwMV-h2DAx298jhWEAAYASAAEgIWm_D_BwE",
      //   icon: faFigma,
      //   color: "#007bff",
      // },
    ],
  },
  {
    title: "Health & Well-being",
    resources: [
      {
        id: 3969,
        name: "Sex Education & Healthy Relationships",
        url: "https://globalgirlsglow.org/how-to-create-a-safe-space-to-teach-sexual-and-reproductive-health/?gclid=Cj0KCQiA8fW9BhC8ARIsACwHqYrMiBKdfVvtYtGA55O5aaT2ZS_2zE4PS225TZOS8k0iP8DNnZWBBYkaAnDfEALw_wcB&utm_source=google&utm_medium=cpc&utm_campaign=GF_Prospecting_PMAX",
        icon: faUserDoctor,
        color: "#007bff",
      },
      {
        id: 3968,
        name: "Healthy eating for adolescents",
        url: "https://www.nidirect.gov.uk/articles/healthy-eating-adolescents",
        icon: faPlus,
        color: "#dc3545",
      },
      {
        id: 3967,
        name: "Nutrition for Teenagers",
        url: "https://www.nutrition.org.uk/nutrition-for/teenagers/",
        icon: faPlus,
        color: "#28a745",
      },
      {
        id: 3965,
        name: "Take Charge of Your Health: A Guide for Teenagers",
        url: "https://www.niddk.nih.gov/health-information/weight-management/take-charge-health-guide-teenagers",
        icon: faNotesMedical,
        color: "#ffc107",
      },
      {
        id: 3964,
        name: "Mental Health",
        url: "https://www.pursuit-of-happiness.org/mental-health-and-wellbeing-toolkit-for-trainers/?gad_source=1&gclid=Cj0KCQiA8fW9BhC8ARIsACwHqYoCePqIjAf86mwkzpnndqwhwJ0JLgwRnmd_1Lq6qbC_3yqe9s2tseoaAnS1EALw_wcB",
        icon: faHeart,
        color: "#fd7e14",
      },
      {
        id: 3960,
        name: "Mental Health & Emotional Resilience",
        url: "Mental Health & Emotional Resilience", // NOTE: You may want to update this broken link
        icon: faBrain,
        color: "#6f42c1",
      },
      {
        id: 3959,
        name: "Advanced Fitness Online Classes",
        url: "https://outschool.com/online-classes/popular/advance-fitness?srsltid=AfmBOoo6Ce9z960xTLcbTnOeDcm3GFM4dlCFJ-dDaozMA9Es53yDTa3i",
        icon: faHeart,
        color: "#17a2b8",
      },
      // {
      //   id: 3958,
      //   name: "Fitness for Both Students and Athletes",
      //   url: "https://advantagefitness.com/high-school-fitness-for-both-students-and-athletes/",
      //   icon: faDumbbell,
      //   color: "#e83e8c",
      // },
    ],
  },
  {
    title: "Fun & Edutainment",
    resources: [
      {
        id: 3989,
        name: "Analyzing augmented reality (AR) and virtual reality (VR) recent development in education",
        url: "https://www.sciencedirect.com/science/article/pii/S2590291123001377",
        icon: faVrCardboard,
        color: "#007bff",
      },
      {
        id: 3988,
        name: "Virtual Reality in Education: Benefits, Tools, and Resources",
        url: "https://soeonline.american.edu/blog/benefits-of-virtual-reality-in-education/",
        icon: faVrCardboard,
        color: "#dc3545",
      },
      {
        id: 3987,
        name: "Virtual Reality in Education",
        url: "https://www.classvr.com/virtual-reality-in-education/",
        icon: faVrCardboard,
        color: "#28a745",
      },
      {
        id: 3986,
        name: "Indian & World Mythology",
        url: "https://www.originaltravel.co.uk/travel-blog/an-introduction-to-myths-and-legends-in-india",
        icon: faGopuram,
        color: "#ffc107",
      },
      {
        id: 3985,
        name: "Indian & Hindu Mythology | Avatars, Stories & Gods",
        url: "https://study.com/academy/lesson/gods-stories-from-indian-mythology.html#:~:text=Trimurti%20is%20a%20triune%20deity,knowledge%2C%20and%20the%20vedic%20texts.",
        icon: faGopuram,
        color: "#fd7e14",
      },
      {
        id: 3984,
        name: "8 Mind-Blowing Space Documentaries to Watch Now on NOVA",
        url: "https://www.pbs.org/wgbh/nova/article/best-space-documentaries-streaming/",
        icon: faFilm,
        color: "#6f42c1",
      },
      {
        id: 3983,
        name: "15 Great Documentary Movies for Middle and High School Classrooms",
        url: "https://www.commonsense.org/education/articles/15-great-documentary-movies-for-middle-and-high-school-classrooms",
        icon: faFilm,
        color: "#17a2b8",
      },
      {
        id: 3982,
        name: "Escape Room Challenge: Minecraft! Logic, Puzzles, Trivia & Riddles",
        url: "https://outschool.com/classes/escape-room-challenge-minecraft-logic-puzzles-trivia-riddles-ages-10-14-YzHNvm3X?srsltid=AfmBOooeMjIny5x_7_5seqSe8BIeibNWA3uc05t_U5IZ-No_oKxd7fdB",
        icon: faDice,
        color: "#e83e8c",
      },
      {
        id: null,
        name: "20 Best Math Puzzles to Engage and Challenge Your Students",
        url: "https://www.prodigygame.com/main-en/blog/math-puzzles/",
        icon: faPuzzlePiece,
        color: "#343a40",
      },
      {
        id: 3980,
        name: "Logical Puzzles & Escape Room Challenges",
        url: "https://learninghypothesis.com/escape-room-puzzle-ideas/",
        icon: faPuzzlePiece,
        color: "#20c997",
      },
    ]
  },


];

function HighSchoolPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      {/* HEADER PART */}
      <h1 className="text-3xl font-bold text-center my-6">High School</h1>

      {data.map((section, index) => (
        <div key={index} className="mb-10 ">
          <h2 className="text-2xl font-semibold mb-4">{section.title}</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {section.resources.map(({ icon, color, name, url }, idx) => (
              <ResourceCardFortAwesome
                key={idx}
                icon={icon}
                color={color}
                name={name}
                url={url}
              />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
};
export default HighSchoolPage;