"use client";

import {
  faFirstdraft,
  faPagelines,
  faPython,
  faSpaceAwesome,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAddressBook,
  faAtom,
  faBaseballBatBall,
  faBook,
  faBookAtlas,
  faBookBookmark,
  faBookOpen,
  faBookOpenReader,
  faBookTanakh,
  faBowlFood,
  faBraille,
  faBrain,
  faBuildingColumns,
  faCameraRetro,
  faCarrot,
  faChalkboardUser,
  faClapperboard,
  faCloudShowersHeavy,
  faCompassDrafting,
  faDemocrat,
  faDrum,
  faEarthAmericas,
  faEarthAsia,
  faEye,
  faFileVideo,
  faFilm,
  faFlask,
  faFlaskVial,
  faFootball,
  faGlobe,
  faGuitar,
  faHandsBubbles,
  faHandSparkles,
  faHeadset,
  faHorseHead,
  faHourglass,
  faIcons,
  faLandmarkDome,
  faLanguage,
  faMasksTheater,
  faMicrophone,
  faMoon,
  faMusic,
  faNewspaper,
  faPen,
  faPenToSquare,
  faPersonChalkboard,
  faPersonRunning,
  faRadio,
  faRecordVinyl,
  faRobot,
  faSackDollar,
  faSchool,
  faSchoolFlag,
  faTableTennisPaddleBall,
  faUserGraduate,
  faUserNinja,
  faUserNurse,
  faUtensils,
  faVials,
  faVolleyball,
} from "@fortawesome/free-solid-svg-icons";
import React from "react";

import { ResourceCardFortAwesome } from "@/components";

const data = [
  {
    title: "Digital Literacy & Tech Skills",
    resources: [
      {
        id: 3796,
        name: "Introduction to AI",
        url: "https://quizmanthon.com/elearn-artificial-intelligence-8.php",
        icon: faBrain,
        color: "#007bff",
      },
      {
        id: 3795,
        name: "Artificial Intelligence Projects, Lessons and Activities",
        url: "https://www.sciencebuddies.org/projects-lessons-activities/artificial-intelligence/sixth-grade",
        icon: faBrain,
        color: "#dc3545",
      },
      {
        id: 3794,
        name: "What Is Artificial Intelligence with Examples & Uses",
        url: "https://www.simplilearn.com/tutorials/artificial-intelligence-tutorial/what-is-artificial-intelligence",
        icon: faBrain,
        color: "#28a745",
      },
      {
        id: 3793,
        name: "Social Media Safety",
        url: "https://rainn.org/safe-media",
        icon: faChalkboardUser,
        color: "#ffc107",
      },
      {
        id: 3792,
        name: "15 ways to use social media for education",
        url: "https://sproutsocial.com/insights/social-media-for-education/",
        icon: faUserGraduate,
        color: "#fd7e14",
      },
      {
        id: 3791,
        name: "Effective Social Media Use for Students",
        url: "https://www.jbcnschool.edu.in/blog/how-to-use-social-media-effectively-for-students/",
        icon: faIcons,
        color: "#6f42c1",
      },
      {
        id: 3790,
        name: "What is Cybersecurity?",
        url: "https://www.kaspersky.com/resource-center/definitions/what-is-cyber-security",
        icon: faGlobe,
        color: "#17a2b8",
      },
      {
        id: 3789,
        name: "Children and Cyber Safety",
        url: "https://www.nls.ac.in/wp-content/uploads/2020/11/Children-and-Cyber-Safety_an-Ebook_-published-on-14-nov-final-anr.pdf",
        icon: faGlobe,
        color: "#e83e8c",
      },
      {
        id: 3788,
        name: "Cyber Awareness",
        url: "https://bbpsnoida.balbharati.org/wp-content/uploads/2016/05/HANDOUTS-CYBER-AWARENESSnew.pdf",
        icon: faGlobe,
        color: "#343a40",
      },
      {
        id: 3778,
        name: "Robotics And Coding: The Complete Beginners Guide",
        url: "https://www.create-learn.us/blog/robotics-and-coding/",
        icon: faRobot,
        color: "#20c997",
      },
      {
        id: null,
        name: "Robotics: What Are Robots?",
        url: "https://builtin.com/robotics",
        icon: faRobot,
        color: "#007bff",
      },
      {
        id: 3771,
        name: "How to Learn Robotics for Kids",
        url: "https://www.create-learn.us/blog/robotics-for-kids/",
        icon: faRobot,
        color: "#dc3545",
      },
      {
        id: 3768,
        name: "Python Robotics – Programming a Robot with Python",
        url: "https://academy.visualcomponents.com/courses/python-robotics-programming-a-robot-with-python/",
        icon: faPython,
        color: "#28a745",
      },
    ],
  },
  {
    title: "Creativity & Performing Arts",
    resources: [
      {
        id: 3841,
        name: "Easy and Fun Paper Craft Ideas for All Ages",
        url: "https://papercraftworld.com/a/blog/paper-craft-ideas?srsltid=AfmBOorEE9-zwlAp5bA--N4Iz_gWsfrdd5k7CXYRq1tEPSFh3jZQVKd4",
        color: "#007bff",
        icon: faDemocrat,
      },
      {
        id: 3837,
        name: "Paper Craft & Origami",
        url: "https://www.creativecenter.brother/en-gb/home/home-category/paper-crafts-origami",
        color: "#dc3545",
        icon: faFirstdraft,
      },
      {
        id: 3835,
        name: "DIY Craft & Origami",
        url: "https://www.instructables.com/Origami-For-Everyone/",
        color: "#28a745",
        icon: faCompassDrafting,
      },
      {
        id: 3833,
        name: "Why students should learn to play a musical instrument",
        url: "https://institute.thememusic.in/why-students-should-learn-to-play-a-musical-instrument/",
        color: "#ffc107",
        icon: faRadio,
      },
      {
        id: 3831,
        name: "musical instruments you can easily learn & play",
        url: "https://medium.com/giglue/top-20-musical-instruments-you-can-easily-play-693f603a2bcf",
        color: "#fd7e14",
        icon: faIcons,
      },
      {
        id: 3830,
        name: "Easiest Instruments to Learn at Any Age",
        url: "https://www.savethemusic.org/blog/easy-instruments-to-learn/",
        color: "#6f42c1",
        icon: faDrum,
      },
      // {
      //   id: 3829,
      //   name: "Instrument Courses",
      //   url: "https://www.shankarmahadevanacademy.com/instruments/",
      //   color: "#17a2b8",
      //   icon: faGuitar,
      // },
      {
        id: 3827,
        name: "Music & Instrument Learning",
        url: "https://meritmusic.org/best-musical-instruments-beginners/",
        color: "#e83e8c",
        icon: faMusic,
      },
      {
        id: 3824,
        name: "Theatre Tales: Drama and Performing Arts in School Curriculum",
        url: "https://www.ssvmws.com/blog/theatre-tales-drama-and-performing-arts-in-school-curriculum/",
        color: "#343a40",
        icon: faFilm,
      },
      {
        id: 3818,
        name: "Theatre Educations",
        url: "https://theatreprofessionals.co.in/education/",
        color: "#20c997",
        icon: faClapperboard,
      },
      {
        id: 3816,
        name: "Drama and Theatre",
        url: "https://www.canadianinternationalschool.com/learning/k-12-programs/drama",
        color: "#007bff",
        icon: faMasksTheater,
      },
      {
        id: 3815,
        name: "Course In Photography & Videography",
        url: "https://ftpinstitute.com/master-diploma-in-photography-and-cinematography/",
        color: "#dc3545",
        icon: faCameraRetro,
      },
      {
        id: 3813,
        name: "Basics of Videography",
        url: "https://alphacommunity.in/the-alpha-classroom/course/4/basics-of-videography/?lesson_id=25&lesson_slug=white-balance",
        color: "#28a745",
        icon: faFileVideo,
      },
      {
        id: 3812,
        name: "Photography & Videography Basics",
        url: "https://teemusphoto.com/tutorials/a-photographers-guide-into-entry-level-videography/",
        color: "#ffc107",
        icon: faRecordVinyl,
      },
    ],
  },
  {
    title: "Health & Well-being",
    resources: [
      {
        id: 3834,
        name: "Puberty and Personal Hygiene Lessons",
        url: "https://salemk12.org/district-departments/student-and-family-supports/health-and-wellness/puberty-and-personal-hygiene-lessons/",
        color: "#007bff",
        icon: faHandSparkles,
      },
      {
        id: 3832,
        name: "Puberty & Personal Hygiene Education",
        url: "https://www.twinkl.co.in/homework-help/science-homework-help/personal-hygiene/why-is-personal-hygiene-important-during-puberty#:~:text=Both%20boys'%20and%20girls'%20bodies,underarms%20and%20between%20the%20legs.",
        color: "#dc3545",
        icon: faHandsBubbles,
      },
      {
        id: 3828,
        name: "7 Nutrition Lesson Plans and Activities",
        url: "https://www.hmhco.com/blog/nutrition-lesson-plans-activities-for-high-school-students?srsltid=AfmBOophAI65PaETMQ5okY1-V4OhUt8ABCmPhN8fxNvV_eDD2loL1zJY",
        color: "#28a745",
        icon: faCarrot,
      },
      {
        id: 3826,
        name: "Healthy Eating Week",
        url: "https://www.nutrition.org.uk/healthy-eating-week/secondary/",
        color: "#ffc107",
        icon: faUtensils,
      },
      {
        id: 3825,
        name: "Nutrition & Healthy Eating",
        url: "https://www.hopkinsmedicine.org/health/wellness-and-prevention/healthy-eating-during-adolescence",
        color: "#fd7e14",
        icon: faBowlFood,
      },
      {
        id: 3823,
        name: "Top 10 Stress Management Techniques",
        url: "https://www.verywellmind.com/top-school-stress-relievers-for-students-3145179",
        color: "#6f42c1",
        icon: faBrain,
      },
      {
        id: 3822,
        name: "The impact of stress",
        url: "https://www.tandfonline.com/doi/full/10.1080/02673843.2019.1596823",
        color: "#17a2b8",
        icon: faBrain,
      },
      {
        id: 3821,
        name: "Stress Management & Mental Health",
        url: "https://theeducationhub.org.nz/understanding-mental-health-and-wellbeing-in-upper-secondary-school-students/",
        color: "#e83e8c",
        icon: faUserNurse,
      },
      {
        id: 3820,
        name: "Sports And Physical Activity",
        url: "https://dalberg.com/wp-content/uploads/2024/09/SoSaPA_report_PRINT_2-Sept.pdf",
        color: "#343a40",
        icon: faPersonRunning,
      },
      {
        id: 3819,
        name: "Importance of Physical Education in Secondary School Curriculum",
        url: "https://globalindianschool.org/noida/blog-details/importance-of-physical-education-in-secondary-school-curriculum",
        color: "#20c997",
        icon: faVolleyball,
      },
      {
        id: 3817,
        name: "Sports and Physical Education",
        url: "https://samagra.education.gov.in/sports.html",
        color: "#007bff",
        icon: faBaseballBatBall,
      },
      {
        id: 3814,
        name: "Sports & Physical Fitness",
        url: "https://nsdcindia.org/nos-listing/40",
        color: "#dc3545",
        icon: faTableTennisPaddleBall,
      },
    ],
  },
  {
    title: "Academic Learning",
    resources: [
      {
        id: 3810,
        name: "Interactive History",
        url: "https://www.historytuition.com/",
        color: "#007bff",
        icon: faBuildingColumns,
      },
      {
        id: 3808,
        name: "Interactive Geography & History",
        url: "https://www.nam.ac.uk/schools/learning-resources/india-empire-and-army-interactive-timeline",
        color: "#dc3545",
        icon: faLandmarkDome,
      },
      {
        id: 3803,
        name: "Interactive Maps of India",
        url: "https://www.mapsofindia.com/maps/",
        color: "#28a745",
        icon: faBookAtlas,
      },
      {
        id: 3787,
        name: "NTSE Preparation Online",
        url: "https://www.ntseguru.in/",
        color: "#ffc107",
        icon: faBaseballBatBall,
      },
      {
        id: 3786,
        name: "Olympiad Exam Preparation",
        url: "https://olympiadhelper.com/?srsltid=AfmBOoo8WM2QN0XBl3v4DPt727VB4krTeqQnuVocFP4Dw39ETF6_Mm4a",
        color: "#fd7e14",
        icon: faFootball,
      },
      {
        id: 3785,
        name: "Olympiads & NTSE Prep",
        url: "https://www.tcyonline.com/tests/ntse-olympiad",
        color: "#6f42c1",
        icon: faVolleyball,
      },
      {
        id: 3783,
        name: "Science & Math Simulations",
        url: "https://phet.colorado.edu/",
        color: "#17a2b8",
        icon: faFlask,
      },
      {
        id: 3780,
        name: "Indian State Education Board Textbook",
        url: "https://kadirkhan.com/indian-state-education-board-textbook-pdf/",
        color: "#e83e8c",
        icon: faBook,
      },
      {
        id: 3776,
        name: "State Board Books",
        url: "https://www.selfstudys.com/page/state-board-books",
        color: "#343a40",
        icon: faBookOpen,
      },
      {
        id: 3773,
        name: "NCERT Books Free PDF",
        url: "https://www.vedantu.com/ncert-books",
        color: "#20c997",
        icon: faBookOpenReader,
      },
      {
        id: 3770,
        name: "NCERT",
        url: "https://ncert.nic.in/textbook.php",
        color: "#007bff",
        icon: faSchool,
      },
      {
        id: 3767,
        name: "Subject-wise Learning",
        url: "https://ncert.nic.in/textbook.php?fesc1=0-16",
        color: "#dc3545",
        icon: faSchool,
      },
      {
        id: 3765,
        name: "Subject-wise Learning",
        url: "https://www.vedantu.com/study-material/cbse-study-material",
        color: "#28a745",
        icon: faBuildingColumns,
      },
      {
        id: 3758,
        name: "Subject-wise Learning",
        url: "https://byjus.com/cbse/cbse-books/",
        color: "#ffc107",
        icon: faSchool,
      },
    ],
  },
  {
    title: "Language & Communication",
    resources: [
      {
        id: 3811,
        name: "Three Language Formula",
        url: "https://www.iitms.co.in/blog/three-language-formula-in-nep-2020.html",
        color: "#007bff",
        icon: faEarthAsia,
      },
      {
        id: 3809,
        name: "Foreign language learning statistics",
        url: "https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Foreign_language_learning_statistics",
        color: "#dc3545",
        icon: faEarthAmericas,
      },
      {
        id: 3807,
        name: "Education in Regional Languages",
        url: "https://collegedunia.com/news/many-parents-in-favour-of-education-in-regional-languages-chinese-dropped-from-list-of-foreign-languages-to-be-taught-at-secondary-level-alertid-24711",
        color: "#28a745",
        icon: faGlobe,
      },
      {
        id: 3806,
        name: "Regional & Foreign Language Learning",
        url: "https://www.educationtimes.com/article/school-guide/99735216/effective-strategies-to-have-classroom-instructions-in-regional-languages",
        color: "#ffc107",
        icon: faLanguage,
      },
      {
        id: 3805,
        name: "Speaking workshop",
        url: "https://indianschoolsdebatingsociety.com/",
        color: "#fd7e14",
        icon: faUserNinja,
      },
      {
        id: 3801,
        name: "Speech and Debate Program",
        url: "https://westminsteru.edu/student-life/speech-and-debate-program.html",
        color: "#6f42c1",
        icon: faMicrophone,
      },
      {
        id: 3799,
        name: "Speech & Debate Clubs",
        url: "https://www.speechdebate.in/?gad_source=1&gclid=CjwKCAiA8Lu9BhA8EiwAag16bx6fcWDr6v-jvMjRfZsltFCo5AhZKLMW4F14NOYmPcNJz3uXXJy0ohoCXJsQAvD_BwE",
        color: "#17a2b8",
        icon: faHeadset,
      },
      {
        id: 3798,
        name: "Book Reviews",
        url: "https://writingcenter.unc.edu/tips-and-tools/book-reviews/",
        color: "#e83e8c",
        icon: faAddressBook,
      },
      {
        id: 3797,
        name: "Book Reviews & Literary Discussions",
        url: "https://independentbookreview.com/2023/01/16/how-to-write-a-great-book-review/",
        color: "#343a40",
        icon: faAddressBook,
      },
      {
        id: 3784,
        name: "Tips To Improve Your Writing Skills",
        url: "https://in.indeed.com/career-advice/career-development/writing-skills",
        color: "#20c997",
        icon: faPenToSquare,
      },
      {
        id: 3782,
        name: "writing-skills",
        url: "https://www.skillsyouneed.com/writing-skills.html",
        color: "#007bff",
        icon: faPen,
      },
      {
        id: 3781,
        name: "Essential Grammar Rules",
        url: "https://prepmaven.com/blog/preparing/essential-grammar-rules/",
        color: "#dc3545",
        icon: faBookOpen,
      },
      {
        id: 3777,
        name: "English Grammar",
        url: "https://www.nationalbookstore.com/books/633-strengthen-english-grammar-for-secondary-.html?srsltid=AfmBOor3E_LZqb_7JjMaqYr1HVLnFlEgdNHHPacpKSIKoMjIT3OyPoee",
        color: "#28a745",
        icon: faBookTanakh,
      },
      {
        id: 3774,
        name: "B1-B2 grammar",
        url: "https://learnenglish.britishcouncil.org/grammar/b1-b2-grammar",
        color: "#ffc107",
        icon: faBookBookmark,
      },
      {
        id: 3769,
        name: "English Grammar & Writing Skills",
        url: "https://globalindianschool.org/ahmedabad/blog-details/tips-to-improve-writing-skills-for-secondary-school-students/",
        color: "#fd7e14",
        icon: faPenToSquare,
      },
    ],
  },
  {
    title: "Fun & Edutainment",
    resources: [
      {
        id: 3860,
        name: "View Space",
        url: "https://viewspace.org/",
        color: "#007bff",
        icon: faEye,
      },
      {
        id: 3858,
        name: "Space Exploration",
        url: "https://spacerenaissance.space/?gad_source=1&gclid=CjwKCAiA8Lu9BhA8EiwAag16b5wGkfzYUVpWQpUn5LYSrnXDucaLetNK7ZsErlRTHMSQoAKqBnSR9hoCrGMQAvD_BwE",
        color: "#dc3545",
        icon: faSpaceAwesome,
      },
      {
        id: 3856,
        name: "Astronomy, Space Science",
        url: "https://space-india.com/astronomy-and-space-education-programs/",
        color: "#28a745",
        icon: faMoon,
      },
      {
        id: 3854,
        name: "Articles About Space and Astronomy",
        url: "https://www.sciencejournalforkids.org/articles/lesson-ideas/space-astronomy/",
        color: "#ffc107",
        icon: faNewspaper,
      },
      {
        id: 3852,
        name: "Folklore, Myths & Legends | Characteristics & Examples",
        url: "https://study.com/learn/lesson/folklore-mythology-examples.html",
        color: "#fd7e14",
        icon: faHorseHead,
      },
      {
        id: 3851,
        name: "Brain Teaser Questions and Answers",
        url: "https://logiclike.com/en/brain-teaser-questions",
        color: "#6f42c1",
        icon: faBrain,
      },
      {
        id: 3850,
        name: "Brain Teaser Questions and Answers",
        url: "https://logiclike.com/en/brain-teaser-questions",
        color: "#17a2b8",
        icon: faBrain,
      },
      {
        id: 3849,
        name: "Brain Teaser Quiz",
        url: "Brain Teaser Quiz",
        color: "#e83e8c",
        icon: faBrain, // This should ideally be faPersonCircleQuestion, but it was malformed in the source HTML
      },
      {
        id: 3848,
        name: "Brain Teasers",
        url: "https://www.buzzfeed.com/in/tag/brain-teasers",
        color: "#343a40",
        icon: faBraille,
      },
      {
        id: 3847,
        name: "Quizzes & Brain Teasers",
        url: "https://www.allprodad.com/brain-teaser-questions-and-answers/",
        color: "#20c997",
        icon: faBrain,
      },
      {
        id: 3846,
        name: "Easy Science Experiments For Young Scientists",
        url: "https://www.21kschool.com/in/blog/science-experiments-for-young-scientists/",
        color: "#007bff",
        icon: faVials,
      },
      {
        id: 3845,
        name: "Easy Science Experiments Using Materials You Already Have On Hand",
        url: "https://www.weareteachers.com/easy-science-experiments/",
        color: "#dc3545",
        icon: faFlask,
      },
      {
        id: 3844,
        name: "Science Experiments",
        url: "https://www.fizzicseducation.com.au/category/150-science-experiments/?srsltid=AfmBOoqXJw6OaiBziPdZj9soL2DQEa3O1B-jVp4S7WbQPkWCb8IDwLuU",
        color: "#28a745",
        icon: faFlaskVial,
      },
      {
        id: 3843,
        name: "Science Experiments at Home",
        url: "https://interactives.ck12.org/simulations/physics.html?utm_source=google&utm_medium=cpc&utm_campaign=Simulations&utm_campaign=9020606872&utm_medium=cpc&utm_source=google&utm_term=science%20simulations&gad_source=1&gclid=CjwKCAiA8Lu9BhA8EiwAag16b6XpRlZFRjzUSZCf8w70aAueCqZk79vCLpJM07WbwtY9NOsw6bFpLRoC_pUQAvD_BwE",
        color: "#ffc107",
        icon: faAtom,
      },
    ],
  },
  {
    title: "Life Skills & Personal Development",
    resources: [
      {
        id: 3910,
        name: "Financial Literacy Booklet",
        url: "https://www.jmcschoolgn.edu.in/images/pdf/Financial-Literacy_Handbook.pdf",
        color: "#007bff",
        icon: faSackDollar,
      },
      {
        id: 3907,
        name: "Financial Education",
        url: "https://ncfe.org.in/wp-content/uploads/2023/12/Class_6th.pdf",
        color: "#dc3545",
        icon: faSackDollar,
      },
      {
        id: 3904,
        name: "Financial Literacy",
        url: "https://cbseacademic.nic.in/web_material/Curriculum22/publication/middle/financial_Literacy_classVIII.pdf",
        color: "#28a745",
        icon: faSackDollar,
      },
      {
        id: 3900,
        name: "Meditation and Emotional Intelligence: An Exploration",
        url: "https://lifecoachtraining.co/meditation-and-emotional-intelligence-an-exploration/",
        color: "#ffc107",
        icon: faBookOpenReader,
      },
      {
        id: 3894,
        name: "6 simple ways to boost your Emotional Intelligence skills",
        url: "https://www.artofliving.org/in-en/lifestyle/well-being/emotional-intelligence",
        color: "#fd7e14",
        icon: faBookOpenReader,
      },
      {
        id: 3892,
        name: "9 Effective Ways for Building Emotional Intelligence in Children",
        url: "https://www.narayanaschools.in/blog/9-effective-ways-for-building-emotional-intelligence-in-children/",
        color: "#6f42c1",
        icon: faBookOpenReader,
      },
      {
        id: 3891,
        name: "Time Management Skills and Techniques for Students",
        url: "https://www.simplilearn.com/tutorials/time-management-tutorial/best-time-management-tips-for-students",
        color: "#17a2b8",
        icon: faHourglass,
      },
      {
        id: 3890,
        name: "Six Steps to Smarter Studying",
        url: "https://kidshealth.org/en/kids/studying.html",
        color: "#e83e8c",
        icon: faHourglass,
      },
      {
        id: 3889,
        name: "11 Good Study Habits to Develop",
        url: "https://www.coursera.org/articles/study-habits",
        color: "#343a40",
        icon: faHourglass,
      },
      {
        id: 3888,
        name: "Mental Ability Test Questions with Answers",
        url: "https://www.indiafolks.com/mat/mental-ability-test-questions-with-answers-for-class-6/",
        color: "#20c997",
        icon: faBookOpen,
      },
      {
        id: 3887,
        name: "Critical Thinking and Problem Solving",
        url: "https://www.utc.edu/academic-affairs/walker-center-for-teaching-and-learning/teaching-resources/pedagogical-strategies-and-techniques/ct-ps",
        color: "#007bff",
        icon: faBookOpen,
      },
      {
        id: 3885,
        name: "6 Main Types of Critical Thinking Skills (With Examples)",
        url: "https://www.indeed.com/career-advice/career-development/critical-thinking-examples",
        color: "#dc3545",
        icon: faBookOpen,
      },
    ],
  },
  {
    title: "Environment & Social Responsibility",
    resources: [
      {
        id: 3870,
        name: "Community Service: Top 10 Reasons to Volunteer",
        url: "https://getinvolved.ucsd.edu/service/resources/reasons.html",
        color: "#007bff",
        icon: faBookOpen,
      },
      {
        id: 3869,
        name: "Volunteerism and Community Service",
        url: "http://khwaahish.in/volunteerism-and-community-service/",
        color: "#dc3545",
        icon: faBuildingColumns,
      },
      {
        id: 3865,
        name: "Top 9 Volunteer Programs in India",
        url: "https://www.goabroad.com/articles/volunteer-abroad/top-volunteer-programs-india",
        color: "#28a745",
        icon: faSchoolFlag,
      },
      {
        id: 3863,
        name: "Top 10 Volunteering Programs for High School Students",
        url: "https://enablingleadership.org/top-10-volunteering-programs-for-high-school-students/",
        color: "#ffc107",
        icon: faBuildingColumns,
      },
      {
        id: 3862,
        name: "Community Service & Volunteering",
        url: "https://volunteeringwithindia.org/#:~:text=VWI%20offers%20affordable%20volunteering%20in,in%20the%20local%20indian%20culture.",
        color: "#fd7e14",
        icon: faBookOpenReader,
      },
      {
        id: 3859,
        name: "Fundamental Duties",
        url: "https://www.nextias.com/blog/fundamental-duties/#:~:text=These%20duties%20include%20respecting%20the,collective%20endeavors%2C%20and%20so%20on.",
        color: "#6f42c1",
        icon: faBookOpenReader,
      },
      // {
      //   id: 3857,
      //   name: "Civic Duties & Rights",
      //   url: "https://knowledgeum.in/blogs/fundamental-rights-and-duties",
      //   color: "#17a2b8",
      //   icon: faBookOpen,
      // },
      {
        id: 3855,
        name: "Fundamental rights and duties in the Indian constitution",
        url: "https://unacademy.com/content/karnataka-psc/study-material/polity/fundamental-rights-and-duties-in-the-indian-constitution/",
        color: "#e83e8c",
        icon: faUserGraduate,
      },
      // {
      //   id: 3853,
      //   name: "Civic Duties & Rights",
      //   url: "https://knowledgeum.in/blogs/fundamental-rights-and-duties",
      //   color: "#343a40",
      //   icon: faSchool,
      // },
      {
        id: 3842,
        name: "Climate change and sustainability education",
        url: "https://journals.uclpress.co.uk/lre/article/pubid/LRE-20-48/",
        color: "#20c997",
        icon: faCloudShowersHeavy,
      },
      {
        id: 3840,
        name: "Climate Change and Environmental Sustainability",
        url: "https://www.unicef.org/india/what-we-do/climate-change",
        color: "#007bff",
        icon: faPagelines,
      },
      {
        id: 3839,
        name: "Climate Change Programme",
        url: "https://dst.gov.in/climate-change-programme",
        color: "#dc3545",
        icon: faSchool,
      },
      {
        id: 3838,
        name: "Climate Change & Sustainability",
        url: "https://journals.uclpress.co.uk/lre/article/pubid/LRE-20-48/",
        color: "#28a745",
        icon: faPersonChalkboard,
      },
    ],
  },
];

function SecondaryPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      {/* HEADER PART */}
      <h1 className="text-3xl font-bold text-center my-6">Secondary</h1>

      {data.map((section, index) => (
        <div key={index} className="mb-10 ">
          <h2 className="text-2xl font-semibold mb-4">{section.title}</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {section.resources.map(({ icon, color, name, url }, idx) => (
              <ResourceCardFortAwesome
                key={idx}
                icon={icon}
                color={color}
                name={name}
                url={url}
              />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

export default SecondaryPage;
